version: '3.8'

services:
  # 1. NestJS Backend Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    ports:
      - "6005:6005"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - NODE_ENV=development
      

      - DATABASE_URL=postgresql://postgres:root@host.docker.internal:5432/teojunping
      
      # Docker Redis Service Name
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
    command: yarn start:dev-swc

  # 2. Redis Cache Service
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: